name: girls_project_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_sms: ^2.3.3
  geolocator: ^13.0.3
  image_picker: ^1.0.7
  permission_handler: ^11.4.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/shieldLogo.jpeg
    - assets/d1.png
    - assets/d2.png
    - assets/d3.png